tasks:
  - init: bash setup.sh "$(gp url 8080)"
    command: |
      curl -fsSL https://deno.land/install.sh | sh
      export DENO_INSTALL="$HOME/.deno"
      export PATH="$DENO_INSTALL/bin:$PATH"
      deno task start
ports:
  - port: 8080
    visibility: public
    onOpen: open-preview
vscode:
  extensions:
    - denoland.vscode-deno
