version: "3"
services:
  app:
    build: .
    init: true
    volumes:
      - ./data:/app/data
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    env_file:
      - .env
    environment:
      - PORT
